version: '3.9'

services:
  web_michat:
    container_name: michat_frontend
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - 3333:80
    environment:
      - VITE_PORT=3333