services:
  michat.database:
    container_name: michat_database
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /var/lib/postgresql/data

  michat_api:
    container_name: michat_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: ["poetry", "run", "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - ${API_BASE_PORT}:8000
    depends_on:
      - michat.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
