"""empty message

Revision ID: 7069eca0cc52
Revises: 329712734055
Create Date: 2025-02-02 01:25:09.378739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7069eca0cc52'
down_revision: Union[str, None] = '329712734055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('fileUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'fileUrl')
    # ### end Alembic commands ###
