"""empty message

Revision ID: 7a8a7d47b0a4
Revises: 
Create Date: 2025-01-20 14:56:50.205584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8a7d47b0a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('idchat', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('idchat')
    )
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('datacreated', sa.Date(), nullable=False),
    sa.Column('dataupdated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_user',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.idchat'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('idmessage', sa.UUID(), nullable=False),
    sa.Column('senderId', sa.UUID(), nullable=False),
    sa.Column('recipientId', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('datecreated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipientId'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('idmessage')
    )
    op.create_table('profiles',
    sa.Column('iduser', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('iduser')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('messages')
    op.drop_table('chat_user')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
