"""empty message

Revision ID: 7da66ac61912
Revises: 7069eca0cc52
Create Date: 2025-02-02 16:14:09.392821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da66ac61912'
down_revision: Union[str, None] = '7069eca0cc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('imgUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'imgUrl')
    # ### end Alembic commands ###
